# Generated by Django 5.1.1 on 2024-09-15 10:44

from django.db import migrations
from django.contrib.postgres.operations import CreateExtension


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        CreateExtension('postgis'),
    ]
