# Generated by Django 5.1.1 on 2024-09-15 11:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('park_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('park_name', models.CharField(max_length=255)),
                ('location_name', models.CharField(max_length=255, verbose_name='Lokasyon Adı')),
                ('park_type_id', models.CharField(max_length=100, verbose_name='Park ID')),
                ('park_type_desc', models.CharField(max_length=100, verbose_name='Park Açıklama')),
                ('capacity_of_park', models.IntegerField(verbose_name='Kapasite')),
                ('working_start_time', models.TimeField(blank=True, null=True, verbose_name='Açılış Saati')),
                ('working_end_time', models.TimeField(blank=True, null=True, verbose_name='Kapanış Saati')),
                ('county_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.county', verbose_name='İlçe')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
