# Generated by Django 5.1.1 on 2024-09-15 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='county',
            old_name='park_name',
            new_name='name',
        ),
    ]
