# Generated by Django 5.1.1 on 2024-09-16 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_park_name_county_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='county',
            options={'verbose_name': 'İlçe', 'verbose_name_plural': 'İlçeler'},
        ),
        migrations.AlterModelOptions(
            name='locations',
            options={'verbose_name': 'Adres', 'verbose_name_plural': 'Adresler'},
        ),
    ]
